//gameValue
import 'package:flutter/material.dart';

List<dynamic> gameValue = [];

//Show text List
Map<String, dynamic> showTextList = {
  "result": [
    {"titile": "Andhar \nBahar", "color": Colors.black},
    {"titile": "A0", "color": Colors.red, "qty": 0},
    {"titile": "A1", "color": Colors.red, "qty": 0},
    {"titile": "A2", "color": Colors.red, "qty": 0},
    {"titile": "A3", "color": Colors.red, "qty": 0},
    {"titile": "A4", "color": Colors.red, "qty": 0},
    {"titile": "A5", "color": Colors.red, "qty": 0},
    {"titile": "A6", "color": Colors.red, "qty": 0},
    {"titile": "A7", "color": Colors.red, "qty": 0},
    {"titile": "A8", "color": Colors.red, "qty": 0},
    {"titile": "A9", "color": Colors.red, "qty": 0},
    {"titile": "B0", "color": Colors.green, "qty": 0},
    {"titile": "00", "color": Colors.black, "qty": 0},
    {"titile": "01", "color": Colors.black, "qty": 0},
    {"titile": "02", "color": Colors.black, "qty": 0},
    {"titile": "03", "color": Colors.black, "qty": 0},
    {"titile": "04", "color": Colors.black, "qty": 0},
    {"titile": "05", "color": Colors.black, "qty": 0},
    {"titile": "06", "color": Colors.black, "qty": 0},
    {"titile": "07", "color": Colors.black, "qty": 0},
    {"titile": "08", "color": Colors.black, "qty": 0},
    {"titile": "09", "color": Colors.black, "qty": 0},
    {"titile": "B1", "color": Colors.green, "qty": 0},
    {"titile": "10", "color": Colors.black, "qty": 0},
    {"titile": "11", "color": Colors.black, "qty": 0},
    {"titile": "12", "color": Colors.black, "qty": 0},
    {"titile": "13", "color": Colors.black, "qty": 0},
    {"titile": "14", "color": Colors.black, "qty": 0},
    {"titile": "15", "color": Colors.black, "qty": 0},
    {"titile": "16", "color": Colors.black, "qty": 0},
    {"titile": "17", "color": Colors.black, "qty": 0},
    {"titile": "18", "color": Colors.black, "qty": 0},
    {"titile": "19", "color": Colors.black, "qty": 0},
    {"titile": "B2", "color": Colors.green, "qty": 0},
    {"titile": "20", "color": Colors.black, "qty": 0},
    {"titile": "21", "color": Colors.black, "qty": 0},
    {"titile": "22", "color": Colors.black, "qty": 0},
    {"titile": "23", "color": Colors.black, "qty": 0},
    {"titile": "24", "color": Colors.black, "qty": 0},
    {"titile": "25", "color": Colors.black, "qty": 0},
    {"titile": "26", "color": Colors.black, "qty": 0},
    {"titile": "27", "color": Colors.black, "qty": 0},
    {"titile": "28", "color": Colors.black, "qty": 0},
    {"titile": "29", "color": Colors.black, "qty": 0},
    {"titile": "B3", "color": Colors.green, "qty": 0},
    {"titile": "30", "color": Colors.black, "qty": 0},
    {"titile": "31", "color": Colors.black, "qty": 0},
    {"titile": "32", "color": Colors.black, "qty": 0},
    {"titile": "33", "color": Colors.black, "qty": 0},
    {"titile": "34", "color": Colors.black, "qty": 0},
    {"titile": "35", "color": Colors.black, "qty": 0},
    {"titile": "36", "color": Colors.black, "qty": 0},
    {"titile": "37", "color": Colors.black, "qty": 0},
    {"titile": "38", "color": Colors.black, "qty": 0},
    {"titile": "39", "color": Colors.black, "qty": 0},
    {"titile": "B4", "color": Colors.green, "qty": 0},
    {"titile": "40", "color": Colors.black, "qty": 0},
    {"titile": "41", "color": Colors.black, "qty": 0},
    {"titile": "42", "color": Colors.black, "qty": 0},
    {"titile": "43", "color": Colors.black, "qty": 0},
    {"titile": "44", "color": Colors.black, "qty": 0},
    {"titile": "45", "color": Colors.black, "qty": 0},
    {"titile": "46", "color": Colors.black, "qty": 0},
    {"titile": "47", "color": Colors.black, "qty": 0},
    {"titile": "48", "color": Colors.black, "qty": 0},
    {"titile": "49", "color": Colors.black, "qty": 0},
    {"titile": "B5", "color": Colors.green, "qty": 0},
    {"titile": "50", "color": Colors.black, "qty": 0},
    {"titile": "51", "color": Colors.black, "qty": 0},
    {"titile": "52", "color": Colors.black, "qty": 0},
    {"titile": "53", "color": Colors.black, "qty": 0},
    {"titile": "54", "color": Colors.black, "qty": 0},
    {"titile": "55", "color": Colors.black, "qty": 0},
    {"titile": "56", "color": Colors.black, "qty": 0},
    {"titile": "57", "color": Colors.black, "qty": 0},
    {"titile": "58", "color": Colors.black, "qty": 0},
    {"titile": "59", "color": Colors.black, "qty": 0},
    {"titile": "B6", "color": Colors.green, "qty": 0},
    {"titile": "60", "color": Colors.black, "qty": 0},
    {"titile": "61", "color": Colors.black, "qty": 0},
    {"titile": "62", "color": Colors.black, "qty": 0},
    {"titile": "63", "color": Colors.black, "qty": 0},
    {"titile": "64", "color": Colors.black, "qty": 0},
    {"titile": "65", "color": Colors.black, "qty": 0},
    {"titile": "66", "color": Colors.black, "qty": 0},
    {"titile": "67", "color": Colors.black, "qty": 0},
    {"titile": "68", "color": Colors.black, "qty": 0},
    {"titile": "69", "color": Colors.black, "qty": 0},
    {"titile": "B7", "color": Colors.green, "qty": 0},
    {"titile": "70", "color": Colors.black, "qty": 0},
    {"titile": "71", "color": Colors.black, "qty": 0},
    {"titile": "72", "color": Colors.black, "qty": 0},
    {"titile": "73", "color": Colors.black, "qty": 0},
    {"titile": "74", "color": Colors.black, "qty": 0},
    {"titile": "75", "color": Colors.black, "qty": 0},
    {"titile": "76", "color": Colors.black, "qty": 0},
    {"titile": "77", "color": Colors.black, "qty": 0},
    {"titile": "78", "color": Colors.black, "qty": 0},
    {"titile": "79", "color": Colors.black, "qty": 0},
    {"titile": "B8", "color": Colors.green, "qty": 0},
    {"titile": "80", "color": Colors.black, "qty": 0},
    {"titile": "81", "color": Colors.black, "qty": 0},
    {"titile": "82", "color": Colors.black, "qty": 0},
    {"titile": "83", "color": Colors.black, "qty": 0},
    {"titile": "84", "color": Colors.black, "qty": 0},
    {"titile": "85", "color": Colors.black, "qty": 0},
    {"titile": "86", "color": Colors.black, "qty": 0},
    {"titile": "87", "color": Colors.black, "qty": 0},
    {"titile": "88", "color": Colors.black, "qty": 0},
    {"titile": "89", "color": Colors.black, "qty": 0},
    {"titile": "B9", "color": Colors.green, "qty": 0},
    {"titile": "90", "color": Colors.black, "qty": 0},
    {"titile": "91", "color": Colors.black, "qty": 0},
    {"titile": "92", "color": Colors.black, "qty": 0},
    {"titile": "93", "color": Colors.black, "qty": 0},
    {"titile": "94", "color": Colors.black, "qty": 0},
    {"titile": "95", "color": Colors.black, "qty": 0},
    {"titile": "96", "color": Colors.black, "qty": 0},
    {"titile": "97", "color": Colors.black, "qty": 0},
    {"titile": "98", "color": Colors.black, "qty": 0},
    {"titile": "99", "color": Colors.black, "qty": 0},
  ]
};

List randomList = [
  "00",
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "80",
  "81",
  "82",
  "83",
  "84",
  "85",
  "86",
  "87",
  "88",
  "89",
  "90",
  "91",
  "92",
  "93",
  "94",
  "95",
  "96",
  "97",
  "98",
  "99",
];

/*

List randomList = [
  "A0",
  "A1",
  "A2",
  "A3",
  "A4",
  "A5",
  "A6",
  "A7",
  "A8",
  "A9",
  "B0",
  "00",
  "01",
  "02",
  "03",
  "04",
  "05",
  "06",
  "07",
  "08",
  "09",
  "B1",
  "10",
  "11",
  "12",
  "13",
  "14",
  "15",
  "16",
  "17",
  "18",
  "19",
  "B2",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "B3",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37",
  "38",
  "39",
  "B4",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "B5",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "B6",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
  "66",
  "67",
  "68",
  "69",
  "B7",
  "70",
  "71",
  "72",
  "73",
  "74",
  "75",
  "76",
  "77",
  "78",
  "79",
  "B8",
  "80",
  "81",
  "82",
  "83",
  "84",
  "85",
  "86",
  "87",
  "88",
  "89",
  "B9",
  "90",
  "91",
  "92",
  "93",
  "94",
  "95",
  "96",
  "97",
  "98",
  "99",
];



*/